### File: nginx.conf
### Desc: Configures URL rewriting. Check out: https://github.com/byuwur/nginx-configurations
### Deps: none
### Copyright (c) 2026 Andrés Trujillo [Mateus] byUwUr

listen 80;
charset utf-8;
#index home.php;
error_page 400 /_error.html?e=400;
error_page 401 /_error.html?e=401;
error_page 403 /_error.html?e=403;
error_page 404 /_error.html?e=404;
error_page 500 /_error.html?e=500;
error_page 502 /_error.html?e=502;
error_page 503 /_error.html?e=503;
error_page 504 /_error.html?e=504;
#access_log  logs/host.access.log  main;